- name: Creating bastion host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import bastion vars
      include_vars: vars/bastion_setup
    - name: import vpc-out vars
      include_vars: vars/vpc_output_vars

    - name: create key pair
      ec2_key:
        name: bastion_key
        region: "{{region}}"
      register: key_out
    - name: save private key
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion_key.pem"
        mode: 0600
      when: key_out.changed
    - name: Creating bastion sec group
      ec2_group:
        name: bastion_sg
        description: Allow ssh
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{my_IP}}"
            rule_desc: allow ssh
      register: bastionSG_out

    - name: creating bastion instance
      ec2:
        key_name: bastion_key
        region: "{{region}}"
        vpc_subnet_id: "{{pubsub2}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        group_id: "{{bastionSG_out.group_id}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: Bastion_host
          Project: Vprofile
        exact_count: 1
        count_tag:
          Name: Bastion_host
          Project: Vprofile
      register: bastionHost_out

    - name: insert bastionSG var to file
      blockinfile:
        path: vars/vpc_out_vars
        backup: yes
        block: |
          BastionSGid: {{bastionSG_out.group_id}}