- name: Creating bastion host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import vpro-stack vars
      include_vars: vars/vpro-stack_setup
    - name: import vpc-out vars
      include_vars: vars/vpc_output_vars

    - name: create key pair
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out
    - name: save private key
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./vprokey.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: SG for Load Balancer
      ec2_group:
        name: vproLB-sg
        description: allow 80
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rule:
          proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
      register: vproLB-sg_out
    - name: SG for vprofile stack
      ec2_group:
        name: vproStack-sg
        description: allow ssh and 80
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
         -  proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{vproLB-sg_out.group_id}}"
         -  proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}"
      register: vproStack-sg_out
    - name: update SG for vprofile stack
      ec2_group:
        name: vproStack-sg
        description: allow ssh and 80
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
         - proto: all
           group_id: "{{vproStack-sg_out.group_id}}"